language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION libopenblas
  - source activate test-environment
  - conda info -a
  - conda list
script:
  - conda install -c f0xy libradtran
  - wget http://www.libradtran.org/download/libradtran-2.0.2.tar.gz
  - tar -xvf libradtran-2.0.2.tar.gz
after_success:
  - cd libRadtran-2.0.2/examples
  - for i in $(ls ./*.INP); do uvspec < $i;done 
